# POST /interactions
POST http://localhost:3000/api/interactions
Content-Type: application/json

{
  "userId": "7bcb58c1-7423-4377-bb44-61fb10fbff30",
  "contentId": "fda3b50f-4e7d-4a1d-994c-18e89ca5735a", 
  "type": "rate",
  "rating": 2
}
